[tool.ruff]
select = [
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    "C", # flake8-comprehensions
    "B", # flake8-bugbear
]

line-length = 119

fix = true

ignore = [
    "B008", # do not perform function calls in argument defaults
    "B006", # Do not use mutable data structures for argument defaults
    "C901", # too complex
    "E402", # module level import (because fo files that modifie sys.path)
    "B904", # required to use "from" when raise an exception
]

target-version = "py311"

unfixable = ["F841"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
"*/migrations/*.py" = ["E501"]

[tool.black]
line-length = 119
