# Generated by Django 5.1.2 on 2024-11-01 02:35

import utils.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='uid',
            field=models.UUIDField(db_default=utils.models.UUID4Generator(), db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='uid',
            field=models.UUIDField(db_default=utils.models.UUID4Generator(), db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
