# Use uma imagem base do Python
FROM python:3.11.4-alpine3.18

# Defina variáveis de ambiente
ENV PYTHONUNBUFFERED 1

# Defina o diretório de trabalho
WORKDIR /app

# Instale dependências do sistema
RUN apk update \
    && apk add --no-cache \
    gcc \
    musl-dev \
    postgresql-dev \
    libpq \
    jpeg-dev \
    zlib-dev

# Copie os arquivos de requisitos
COPY requirements/ /app/requirements/

# Instale as dependências do Python
RUN pip install --upgrade pip \
    && pip install -r requirements/prod.txt

# Copie o código da aplicação
COPY . /app/

EXPOSE 8000

# Comando para rodar a aplicação
CMD ["granian", "--interface", "wgsi", "src.core.wsgi:application" "--port", "8000", "--host", "0.0.0.0", "--workers","4",  "--log-level", "debug"]

